#! /usr/bin/env python3
"""
tests/test_equivalence.py
=========================

Proves the *scientific logic is unchanged* by the refactor: results from the
new thematic ``mosna`` package match the original monolithic implementation
bit-for-bit on a battery of pure functions and the synthetic test networks.

The pristine original module is read from the source git history into a temp
file and imported side-by-side with the refactored package. Run with::

    pytest tests/test_equivalence.py

If the original source tree has been deleted, the comparison tests are skipped
(the package-internal sanity tests still run).
"""

import importlib.util
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import mosna as new

# Location where the equivalence harness expects a copy of the original module.
# Generated by: `git show HEAD:mosna/mosna.py > tests/_orig_mosna_reference.py`
# from the upstream source tree before it was deleted.
_ORIG = Path(__file__).resolve().parent / "_orig_mosna_reference.py"


@pytest.fixture(scope="module")
def orig():
    if not _ORIG.exists():
        pytest.skip("original reference module not present; comparison skipped")
    spec = importlib.util.spec_from_file_location("orig_mosna", _ORIG)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


TEST_NETS = [
    "make_triangonal_net", "make_trigonal_net", "make_P_net",
    "make_high_assort_net", "make_high_disassort_net",
]


@pytest.mark.parametrize("net", TEST_NETS)
def test_test_networks_identical(orig, net):
    no, eo = getattr(orig, net)()
    nn, en = getattr(new, net)()
    np.testing.assert_array_equal(no.values, nn.values)
    np.testing.assert_array_equal(eo.values, en.values)


def test_assortativity_pipeline(orig):
    nodes, edges = orig.make_high_assort_net()
    attrs = ["a", "b", "c"]
    M_o = orig.mixing_matrix(nodes, edges, attrs)
    M_n = new.mixing_matrix(nodes, edges, attrs)
    np.testing.assert_allclose(M_o, M_n, rtol=1e-12, atol=1e-12)
    assert orig.attribute_ac(M_o) == new.attribute_ac(M_n)
    assert (orig.count_edges_undirected(nodes, edges, ["a", "b"])
            == new.count_edges_undirected(nodes, edges, ["a", "b"]))
    assert orig.mixmat_to_columns(M_o) == new.mixmat_to_columns(M_n)
    assert orig.attributes_pairs(attrs) == new.attributes_pairs(attrs)


def test_transforms(orig):
    rng = np.random.default_rng(0)
    X = np.abs(rng.random((20, 5))) + 0.1
    np.testing.assert_allclose(orig.transform_logp1(X), new.transform_logp1(X))
    np.testing.assert_allclose(orig.transform_CLR(X), new.transform_CLR(X))
    np.testing.assert_allclose(orig.renormalize(X, 0, 1), new.renormalize(X, 0, 1))


def test_neighbors_k_order(orig):
    nodes, edges = orig.make_high_assort_net()
    pairs = edges.values
    assert repr(orig.neighbors_k_order(pairs, 0, 2)) == \
           repr(new.neighbors_k_order(pairs, 0, 2))


def test_zscore(orig):
    rng = np.random.default_rng(1)
    m, mr = rng.random((3, 3)), rng.random((10, 3, 3))
    np.testing.assert_allclose(orig.zscore(m, mr), new.zscore(m, mr))


# ---- package-internal sanity (run even without the original reference) ----

def test_flat_and_themed_api_present():
    for name in ["mixing_matrix", "groups_assort_mixmat", "get_clusterer",
                 "plot_clusters", "logistic_regression", "make_features_NAS",
                 "transform_data", "screen_nas_parameters"]:
        assert hasattr(new, name), name
    from mosna.assortativity import mixing_matrix  # themed
    from mosna.mosna import mixing_matrix as legacy  # legacy shim
    assert mixing_matrix is legacy
