#! /usr/bin/env python3
"""
tests/test_equivalence.py
=========================

Proves the *scientific logic is unchanged* by the refactor: results from the
new thematic ``mosna`` package match the original monolithic implementation
bit-for-bit on a battery of pure functions and the synthetic test networks.

The pristine original module is read from the source git history into a temp
file and imported side-by-side with the refactored package. Run with::

    pytest tests/test_equivalence.py

If the original source tree has been deleted, the comparison tests are skipped
(the package-internal sanity tests still run).
"""

import importlib.util
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import mosna as new

# Location where the equivalence harness expects a copy of the original module.
# Generated by: `git show HEAD:mosna/mosna.py > tests/_orig_mosna_reference.py`
# from the upstream source tree before it was deleted.
_ORIG = Path(__file__).resolve().parent / "_orig_mosna_reference.py"


@pytest.fixture(scope="module")
def orig():
    if not _ORIG.exists():
        pytest.skip("original reference module not present; comparison skipped")
    spec = importlib.util.spec_from_file_location("orig_mosna", _ORIG)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


TEST_NETS = [
    "make_triangonal_net", "make_trigonal_net", "make_P_net",
    "make_high_assort_net", "make_high_disassort_net",
]


@pytest.mark.parametrize("net", TEST_NETS)
def test_test_networks_identical(orig, net):
    no, eo = getattr(orig, net)()
    nn, en = getattr(new, net)()
    np.testing.assert_array_equal(no.values, nn.values)
    np.testing.assert_array_equal(eo.values, en.values)


def test_assortativity_pipeline(orig):
    nodes, edges = orig.make_high_assort_net()
    attrs = ["a", "b", "c"]
    M_o = orig.mixing_matrix(nodes, edges, attrs)
    M_n = new.mixing_matrix(nodes, edges, attrs)
    np.testing.assert_allclose(M_o, M_n, rtol=1e-12, atol=1e-12)
    assert orig.attribute_ac(M_o) == new.attribute_ac(M_n)
    assert (orig.count_edges_undirected(nodes, edges, ["a", "b"])
            == new.count_edges_undirected(nodes, edges, ["a", "b"]))
    assert orig.mixmat_to_columns(M_o) == new.mixmat_to_columns(M_n)
    assert orig.attributes_pairs(attrs) == new.attributes_pairs(attrs)


def test_transforms(orig):
    rng = np.random.default_rng(0)
    X = np.abs(rng.random((20, 5))) + 0.1
    np.testing.assert_allclose(orig.transform_logp1(X), new.transform_logp1(X))
    np.testing.assert_allclose(orig.transform_CLR(X), new.transform_CLR(X))
    np.testing.assert_allclose(orig.renormalize(X, 0, 1), new.renormalize(X, 0, 1))


@pytest.mark.parametrize("n,ne,nv", [(200, 600, 5), (1000, 4000, 8), (3000, 15000, 10)])
def test_aggregate_k_neighbors_order1_vectorized(orig, n, ne, nv):
    """The vectorised order-1 mean/std path must equal the original per-node
    loop bit-for-bit (up to floating-point noise)."""
    rng = np.random.default_rng(n)
    X = rng.random((n, nv))
    e = rng.integers(0, n, (ne, 2))
    e = e[e[:, 0] != e[:, 1]]
    pairs = np.unique(np.sort(e, axis=1), axis=0)
    vn = [f"v{i}" for i in range(nv)]
    o = orig.aggregate_k_neighbors(X, pairs, order=1, var_names=vn)
    v = new.aggregate_k_neighbors(X, pairs, order=1, var_names=vn)
    np.testing.assert_allclose(o[o.columns].values, v[o.columns].values,
                               rtol=1e-9, atol=1e-9)


def test_aggregate_k_neighbors_isolated_node(orig):
    """A node with no edges aggregates over only itself, in both versions."""
    rng = np.random.default_rng(0)
    X = rng.random((5, 3))
    pairs = np.array([[0, 1], [1, 2]])  # nodes 3, 4 isolated
    vn = ["a", "b", "c"]
    o = orig.aggregate_k_neighbors(X, pairs, order=1, var_names=vn)
    v = new.aggregate_k_neighbors(X, pairs, order=1, var_names=vn)
    np.testing.assert_allclose(o.values, v.values, rtol=1e-12, atol=1e-12)


def test_aggregate_k_neighbors_fallback_paths(orig):
    """order=2 and custom statistics must still match the original (loop path)."""
    rng = np.random.default_rng(1)
    n, nv = 300, 4
    X = rng.random((n, nv))
    e = rng.integers(0, n, (1200, 2))
    e = e[e[:, 0] != e[:, 1]]
    pairs = np.unique(np.sort(e, axis=1), axis=0)
    vn = [f"v{i}" for i in range(nv)]
    # higher order -> loop fallback
    np.testing.assert_allclose(
        orig.aggregate_k_neighbors(X, pairs, order=2, var_names=vn).values,
        new.aggregate_k_neighbors(X, pairs, order=2, var_names=vn).values,
        rtol=1e-9, atol=1e-9)
    # custom stats -> loop fallback
    np.testing.assert_allclose(
        orig.aggregate_k_neighbors(X, pairs, order=1, var_names=vn,
            stat_funcs=[np.mean, np.max], stat_names=['mean', 'max']).values,
        new.aggregate_k_neighbors(X, pairs, order=1, var_names=vn,
            stat_funcs=[np.mean, np.max], stat_names=['mean', 'max']).values,
        rtol=1e-9, atol=1e-9)


def test_neighbors_k_order(orig):
    nodes, edges = orig.make_high_assort_net()
    pairs = edges.values
    assert repr(orig.neighbors_k_order(pairs, 0, 2)) == \
           repr(new.neighbors_k_order(pairs, 0, 2))


def test_zscore(orig):
    rng = np.random.default_rng(1)
    m, mr = rng.random((3, 3)), rng.random((10, 3, 3))
    np.testing.assert_allclose(orig.zscore(m, mr), new.zscore(m, mr))


def test_mixing_matrix_vectorized_matches_original(orig):
    """The vectorised mixing_matrix must equal the original loop bit-for-bit,
    including on a multi-attribute graph with normalisation & double diagonal."""
    rng = np.random.default_rng(3)
    n, A = 2000, 6
    coords = rng.random((n, 2))
    onehot = np.zeros((n, A), dtype=int)
    onehot[np.arange(n), rng.integers(0, A, n)] = 1
    attrs = [f"t{i}" for i in range(A)]
    nodes = pd.concat(
        [pd.DataFrame(coords, columns=["x", "y"]),
         pd.DataFrame(onehot, columns=attrs)], axis=1)
    e = rng.integers(0, n, (5000, 2))
    edges = pd.DataFrame(np.unique(e, axis=0), columns=["source", "target"])
    for norm in (True, False):
        for dd in (True, False):
            np.testing.assert_array_equal(
                orig.mixing_matrix(nodes, edges, attrs, normalized=norm, double_diag=dd),
                new.mixing_matrix(nodes, edges, attrs, normalized=norm, double_diag=dd),
            )


def _onehot_graph(seed=4, n=1500, A=5, n_edges=4000):
    rng = np.random.default_rng(seed)
    onehot = np.zeros((n, A), dtype=int)
    onehot[np.arange(n), rng.integers(0, A, n)] = 1
    attrs = [f"t{i}" for i in range(A)]
    nodes = pd.DataFrame(onehot, columns=attrs)
    e = rng.integers(0, n, (n_edges, 2))
    edges = pd.DataFrame(np.unique(e, axis=0), columns=["source", "target"])
    return nodes, edges, attrs


def test_randomized_mixmat_serial_reproducible():
    """The fast serial path is reproducible for a fixed random_state."""
    nodes, edges, attrs = _onehot_graph()
    mm1, ac1 = new.randomized_mixmat(
        nodes, edges, attrs, n_shuffle=8, parallel=False, verbose=0, random_state=7)
    mm2, ac2 = new.randomized_mixmat(
        nodes, edges, attrs, n_shuffle=8, parallel=False, verbose=0, random_state=7)
    np.testing.assert_array_equal(mm1, mm2)
    np.testing.assert_array_equal(ac1, ac2)


def test_randomized_mixmat_fast_path_matches_mixing_matrix():
    """Each shuffle of the fast codes path equals mixing_matrix applied to the
    same permuted labels — i.e. the fast path computes the *exact* mixing matrix
    of a shuffled network, just without the DataFrame round-trip."""
    nodes, edges, attrs = _onehot_graph()
    A = len(attrs)
    codes = nodes[attrs].values.argmax(1)

    # reproduce the first shuffle the fast path would draw
    rng = np.random.default_rng(123)
    shuffled = rng.permutation(codes)
    shuffled_nodes = pd.DataFrame(np.eye(A, dtype=int)[shuffled], columns=attrs)
    expected = new.mixing_matrix(shuffled_nodes, edges, attrs)

    # first matrix produced by randomized_mixmat with the same seed
    mm, _ = new.randomized_mixmat(
        nodes, edges, attrs, n_shuffle=1, parallel=False, verbose=0, random_state=123)
    np.testing.assert_allclose(mm[0], expected, rtol=1e-12, atol=1e-12)


def test_randomized_mixmat_statistically_equivalent_to_original(orig):
    """Over many shuffles, the fast path's mean mixing matrix matches the
    original implementation's mean (same distribution, different draws)."""
    nodes, edges, attrs = _onehot_graph(n=800, A=4, n_edges=3000)
    ns = 400
    mm_new, _ = new.randomized_mixmat(
        nodes, edges, attrs, n_shuffle=ns, parallel=False, verbose=0, random_state=0)
    mm_orig, _ = orig.randomized_mixmat(
        nodes, edges, attrs, n_shuffle=ns, parallel=False, verbose=0)
    # means over the shuffle axis should agree to a loose Monte-Carlo tolerance
    np.testing.assert_allclose(mm_new.mean(0), mm_orig.mean(0), atol=2e-3)


# ---- package-internal sanity (run even without the original reference) ----

def test_flat_and_themed_api_present():
    for name in ["mixing_matrix", "groups_assort_mixmat", "get_clusterer",
                 "plot_clusters", "logistic_regression", "make_features_NAS",
                 "transform_data", "screen_nas_parameters"]:
        assert hasattr(new, name), name
    from mosna.assortativity import mixing_matrix  # themed
    from mosna.mosna import mixing_matrix as legacy  # legacy shim
    assert mixing_matrix is legacy
